services:
  expo:
    build: .
    image: expo-dev:latest
    working_dir: /app
    volumes:
      - ./:/app
      - expo_node_modules:/app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    stdin_open: true
    tty: true
  cli:
    build: .
    image: expo-dev:latest
    working_dir: /app
    volumes:
      - ./:/app
      - expo_node_modules:/app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true

volumes:
  expo_node_modules:
